# Generated by Django 5.1 on 2025-04-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_link', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=True)),
                ('guide_approved', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guide')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foreign_viva', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Synopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=True)),
                ('guide_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Viva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('viva_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_1_projects', to='projects.evaluator')),
                ('viva_2', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_2_projects', to='projects.evaluator')),
            ],
        ),
    ]
