# Generated by Django 5.1 on 2025-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_link',
            field=models.URLField(null=True),
        ),
    ]
