# Generated by Django 5.1 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='synopsis',
            name='title',
            field=models.CharField(default='my synopsis title', max_length=200),
            preserve_default=False,
        ),
    ]
