# Generated by Django 5.1 on 2025-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_synopsis_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='synopsis',
            name='file_link',
            field=models.CharField(max_length=200),
        ),
    ]
